name: Email Notification

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
      - name: Send email
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          secure: true
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: "GitHub Repo Update"
          bcc: tharvesh2026@gmail.com,tharveshmuhaideen@gmail.com,tmnexus.offi@gmail.com
          from: I.Core Project Update <imtharvesh@gmail.com>
          body: |
            New App Published in I.Core projects - https://icore-projects.github.io .

            Repository: ${{ github.repository }}
            Event: ${{ github.event_name }}
            Branch: ${{ github.ref_name }}
            Actor: ${{ github.actor }}

            Message:
            ${{ github.event.head_commit.message || github.event.pull_request.title }}

            View run:
            https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}
